package utils

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_demo "github.com/lucasew/workspaced/cmd/workspaced/utils/demo"
	pkg_history "github.com/lucasew/workspaced/cmd/workspaced/utils/history"
	pkg_icons "github.com/lucasew/workspaced/cmd/workspaced/utils/icons"
	pkg_nix "github.com/lucasew/workspaced/cmd/workspaced/utils/nix"
	pkg_palette "github.com/lucasew/workspaced/cmd/workspaced/utils/palette"
	pkg_shell "github.com/lucasew/workspaced/cmd/workspaced/utils/shell"
	pkg_template "github.com/lucasew/workspaced/cmd/workspaced/utils/template"
)

func init() {
	Registry.FromGetter(pkg_demo.GetCommand)
	Registry.FromGetter(pkg_history.GetCommand)
	Registry.FromGetter(pkg_icons.GetCommand)
	Registry.FromGetter(pkg_nix.GetCommand)
	Registry.FromGetter(pkg_palette.GetCommand)
	Registry.FromGetter(pkg_shell.GetCommand)
	Registry.FromGetter(pkg_template.GetCommand)
}
