package utils

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_demo "github.com/lucasew/workspaced/cmd/workspaced/utils/demo"
	pkg_history "github.com/lucasew/workspaced/cmd/workspaced/utils/history"
	pkg_icons "github.com/lucasew/workspaced/cmd/workspaced/utils/icons"
	pkg_nix "github.com/lucasew/workspaced/cmd/workspaced/utils/nix"
	pkg_palette "github.com/lucasew/workspaced/cmd/workspaced/utils/palette"
	pkg_shell "github.com/lucasew/workspaced/cmd/workspaced/utils/shell"
	pkg_template "github.com/lucasew/workspaced/cmd/workspaced/utils/template"
)

type children struct {
	Demo     *pkg_demo.Command
	History  *pkg_history.Command
	Icons    *pkg_icons.Command
	Nix      *pkg_nix.Command
	Palette  *pkg_palette.Command
	Shell    *pkg_shell.Command
	Template *pkg_template.Command
}
