package codebase

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_config "workspaced/cmd/workspaced/codebase/config"
)

func init() {
	Registry.FromGetter(pkg_config.GetCommand)
}
