# Warning: Do not unify this file with others. Keep tool definitions localized.
[tools]
go = "1.26.0"
"go:golang.org/x/tools/gopls" = "0.21.0"
goreleaser = "2.14.1"
svu = "3.3.0"
"github:lucasew/workspaced" = "0.2.1"

[tasks.install]
depends = ["install:*"]

[tasks."install:go"]
run = "go mod download"

[tasks.test]
depends = ["test:*"]

[tasks."test:go"]
run = "go test -v ./..."

[tasks.lint]
run = "workspaced codebase lint"

[tasks.fmt]
run = "workspaced codebase format"

[tasks.codegen]
depends = ["codegen:*"]

[tasks."codegen:go"]
run = "go generate ./..."

[tasks.ci]
depends = ["lint", "test"]

[tasks.release]
description = "Run a release"
depends = ["codegen", "ci"]
wait_for = ["codegen"]
usage = '''
arg "<version>" help="New version" {
  choices "next" "major" "minor" "patch"
  default "next"
}
'''
run = '''
git tag $(svu ${usage_version})
goreleaser release --clean
'''
