package driver

// this file is generated by pkg/devtools/autoregistry.go, do not edit manually
import (
	pkg_audio "workspaced/cmd/workspaced/driver/audio"
	pkg_brightness "workspaced/cmd/workspaced/driver/brightness"
	pkg_doctor "workspaced/cmd/workspaced/driver/doctor"
	pkg_input "workspaced/cmd/workspaced/driver/input"
	pkg_media "workspaced/cmd/workspaced/driver/media"
	pkg_notification "workspaced/cmd/workspaced/driver/notification"
	pkg_open "workspaced/cmd/workspaced/driver/open"
	pkg_power "workspaced/cmd/workspaced/driver/power"
	pkg_screen "workspaced/cmd/workspaced/driver/screen"
	pkg_screenshot "workspaced/cmd/workspaced/driver/screenshot"
	pkg_sudo "workspaced/cmd/workspaced/driver/sudo"
	pkg_wallpaper "workspaced/cmd/workspaced/driver/wallpaper"
	pkg_workspace "workspaced/cmd/workspaced/driver/workspace"
)

func init() {
	Registry.FromGetter(pkg_audio.GetCommand)
	Registry.FromGetter(pkg_brightness.GetCommand)
	Registry.FromGetter(pkg_doctor.GetCommand)
	Registry.FromGetter(pkg_input.GetCommand)
	Registry.FromGetter(pkg_media.GetCommand)
	Registry.FromGetter(pkg_notification.GetCommand)
	Registry.FromGetter(pkg_open.GetCommand)
	Registry.FromGetter(pkg_power.GetCommand)
	Registry.FromGetter(pkg_screen.GetCommand)
	Registry.FromGetter(pkg_screenshot.GetCommand)
	Registry.FromGetter(pkg_sudo.GetCommand)
	Registry.FromGetter(pkg_wallpaper.GetCommand)
	Registry.FromGetter(pkg_workspace.GetCommand)
}
