package driver

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_audio "github.com/lucasew/workspaced/cmd/workspaced/driver/audio"
	pkg_brightness "github.com/lucasew/workspaced/cmd/workspaced/driver/brightness"
	pkg_camera "github.com/lucasew/workspaced/cmd/workspaced/driver/camera"
	pkg_doctor "github.com/lucasew/workspaced/cmd/workspaced/driver/doctor"
	pkg_input "github.com/lucasew/workspaced/cmd/workspaced/driver/input"
	pkg_media "github.com/lucasew/workspaced/cmd/workspaced/driver/media"
	pkg_notification "github.com/lucasew/workspaced/cmd/workspaced/driver/notification"
	pkg_open "github.com/lucasew/workspaced/cmd/workspaced/driver/open"
	pkg_power "github.com/lucasew/workspaced/cmd/workspaced/driver/power"
	pkg_rsync "github.com/lucasew/workspaced/cmd/workspaced/driver/rsync"
	pkg_screen "github.com/lucasew/workspaced/cmd/workspaced/driver/screen"
	pkg_screenshot "github.com/lucasew/workspaced/cmd/workspaced/driver/screenshot"
	pkg_sudo "github.com/lucasew/workspaced/cmd/workspaced/driver/sudo"
	pkg_wallpaper "github.com/lucasew/workspaced/cmd/workspaced/driver/wallpaper"
	pkg_workspace "github.com/lucasew/workspaced/cmd/workspaced/driver/workspace"
)

func init() {
	Registry.FromGetter(pkg_audio.GetCommand)
	Registry.FromGetter(pkg_brightness.GetCommand)
	Registry.FromGetter(pkg_camera.GetCommand)
	Registry.FromGetter(pkg_doctor.GetCommand)
	Registry.FromGetter(pkg_input.GetCommand)
	Registry.FromGetter(pkg_media.GetCommand)
	Registry.FromGetter(pkg_notification.GetCommand)
	Registry.FromGetter(pkg_open.GetCommand)
	Registry.FromGetter(pkg_power.GetCommand)
	Registry.FromGetter(pkg_rsync.GetCommand)
	Registry.FromGetter(pkg_screen.GetCommand)
	Registry.FromGetter(pkg_screenshot.GetCommand)
	Registry.FromGetter(pkg_sudo.GetCommand)
	Registry.FromGetter(pkg_wallpaper.GetCommand)
	Registry.FromGetter(pkg_workspace.GetCommand)
}
