package driver

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_audio "github.com/lucasew/workspaced/cmd/workspaced/driver/audio"
	pkg_brightness "github.com/lucasew/workspaced/cmd/workspaced/driver/brightness"
	pkg_camera "github.com/lucasew/workspaced/cmd/workspaced/driver/camera"
	pkg_doctor "github.com/lucasew/workspaced/cmd/workspaced/driver/doctor"
	pkg_input "github.com/lucasew/workspaced/cmd/workspaced/driver/input"
	pkg_media "github.com/lucasew/workspaced/cmd/workspaced/driver/media"
	pkg_notification "github.com/lucasew/workspaced/cmd/workspaced/driver/notification"
	pkg_open "github.com/lucasew/workspaced/cmd/workspaced/driver/open"
	pkg_power "github.com/lucasew/workspaced/cmd/workspaced/driver/power"
	pkg_rsync "github.com/lucasew/workspaced/cmd/workspaced/driver/rsync"
	pkg_screen "github.com/lucasew/workspaced/cmd/workspaced/driver/screen"
	pkg_screenshot "github.com/lucasew/workspaced/cmd/workspaced/driver/screenshot"
	pkg_sudo "github.com/lucasew/workspaced/cmd/workspaced/driver/sudo"
	pkg_wallpaper "github.com/lucasew/workspaced/cmd/workspaced/driver/wallpaper"
	pkg_workspace "github.com/lucasew/workspaced/cmd/workspaced/driver/workspace"
)

type children struct {
	Audio        *pkg_audio.Command
	Brightness   *pkg_brightness.Command
	Camera       *pkg_camera.Command
	Doctor       *pkg_doctor.Command
	Input        *pkg_input.Command
	Media        *pkg_media.Command
	Notification *pkg_notification.Command
	Open         *pkg_open.Command
	Power        *pkg_power.Command
	Rsync        *pkg_rsync.Command
	Screen       *pkg_screen.Command
	Screenshot   *pkg_screenshot.Command
	Sudo         *pkg_sudo.Command
	Wallpaper    *pkg_wallpaper.Command
	Workspace    *pkg_workspace.Command
}
