// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

type History struct {
	ID         int64
	Command    string
	Cwd        string
	Timestamp  int64
	ExitCode   int64
	DurationMs int64
}
