// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlite

import (
	"context"
)

type Querier interface {
	GetHistory(ctx context.Context, limit int64) ([]History, error)
	RecordHistory(ctx context.Context, arg RecordHistoryParams) error
	SearchHistory(ctx context.Context, arg SearchHistoryParams) ([]History, error)
}

var _ Querier = (*Queries)(nil)
