package termux

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"workspaced/pkg/api"
	"workspaced/pkg/driver"
	execdriver "workspaced/pkg/driver/exec"
	"workspaced/pkg/types"
)

type Provider struct{}

func (p *Provider) ID() string {
	return "exec_termux"
}

func (p *Provider) Name() string {
	return "Termux"
}

func (p *Provider) DefaultWeight() int {
	// Higher weight than native driver (50) to ensure Termux driver is preferred on Android
	return 60
}

func (p *Provider) CheckCompatibility(ctx context.Context) error {
	// Check if we're running in Termux
	if os.Getenv("TERMUX_VERSION") == "" {
		return fmt.Errorf("%w: not running in Termux", driver.ErrIncompatible)
	}
	return nil
}

func (p *Provider) New(ctx context.Context) (execdriver.Driver, error) {
	return &Driver{}, nil
}

type Driver struct{}

func (d *Driver) Run(ctx context.Context, name string, args ...string) *exec.Cmd {
	// Fix DNS resolution for child processes in Termux
	resolvPath, err := ensureResolvConf()
	if err != nil {
		slog.Warn("failed to setup resolv.conf", "error", err)
	} else {
		slog.Debug("resolv.conf configured", "path", resolvPath)
	}

	// Fix SSL certificates for child processes in Termux
	certPath, err := ensureSSLCerts()
	if err != nil {
		slog.Warn("failed to setup SSL certificates", "error", err)
	} else {
		slog.Debug("SSL certificates configured", "path", certPath)
	}

	// Resolve the full path using custom Which to avoid SIGSYS on Android
	fullPath, err := d.Which(ctx, name)
	if err != nil {
		// If Which fails, fall back to the original name
		fullPath = name
	}

	// Use termux-chroot (always available in Termux, wraps proot with proper binds)
	chrootPath, err := d.Which(ctx, "termux-chroot")
	if err != nil {
		slog.Warn("termux-chroot not found (should be installed in Termux)", "error", err)
		// Fallback to running without chroot if somehow not available
		cmd := exec.CommandContext(ctx, fullPath, args...)
		return cmd
	}

	// Build command string for termux-chroot
	// termux-chroot expects: termux-chroot "command args..."
	cmdStr := fullPath
	for _, arg := range args {
		// Quote arguments that contain spaces
		if strings.Contains(arg, " ") {
			cmdStr += " \"" + arg + "\""
		} else {
			cmdStr += " " + arg
		}
	}

	slog.Debug("using termux-chroot for command execution", "command", cmdStr)
	cmd := exec.CommandContext(ctx, chrootPath, cmdStr)
	return cmd
}

// ensureResolvConf creates /etc/resolv.conf in Termux PREFIX if it doesn't exist or is broken
func ensureResolvConf() (string, error) {
	// Get Termux PREFIX (usually /data/data/com.termux/files/usr)
	prefix := os.Getenv("PREFIX")
	if prefix == "" {
		prefix = "/data/data/com.termux/files/usr"
	}

	resolvConfPath := filepath.Join(prefix, "etc", "resolv.conf")

	// Check if resolv.conf exists and has valid content
	if content, err := os.ReadFile(resolvConfPath); err == nil {
		contentStr := string(content)
		// Check if it has our nameserver entries
		if strings.Contains(contentStr, "8.8.8.8") {
			slog.Debug("resolv.conf already configured", "path", resolvConfPath)
			return resolvConfPath, nil
		}
	}

	// Create or overwrite with working DNS servers
	dnsConfig := `# Generated by workspaced for Termux DNS resolution
nameserver 8.8.8.8
nameserver 8.8.4.4
nameserver 1.1.1.1
`

	// Ensure etc directory exists
	etcDir := filepath.Join(prefix, "etc")
	if err := os.MkdirAll(etcDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create etc directory: %w", err)
	}

	// Write resolv.conf
	if err := os.WriteFile(resolvConfPath, []byte(dnsConfig), 0644); err != nil {
		return "", fmt.Errorf("failed to write resolv.conf: %w", err)
	}

	slog.Info("created resolv.conf for Termux DNS", "path", resolvConfPath)

	// Verify it was written
	if content, err := os.ReadFile(resolvConfPath); err != nil {
		slog.Error("failed to verify resolv.conf after writing", "error", err)
	} else {
		slog.Info("resolv.conf content verified", "size", len(content))
	}

	return resolvConfPath, nil
}

// ensureSSLCerts sets up SSL certificates in standard locations for termux-chroot
func ensureSSLCerts() (string, error) {
	prefix := os.Getenv("PREFIX")
	if prefix == "" {
		prefix = "/data/data/com.termux/files/usr"
	}

	// Source: Termux CA bundle
	sourceCert := filepath.Join(prefix, "etc", "tls", "cert.pem")
	if _, err := os.Stat(sourceCert); err != nil {
		return "", fmt.Errorf("termux CA bundle not found at %s: %w", sourceCert, err)
	}

	// Target: Standard location that most SSL libraries check
	// In termux-chroot, $PREFIX/etc becomes /etc
	sslDir := filepath.Join(prefix, "etc", "ssl", "certs")
	targetCert := filepath.Join(sslDir, "ca-certificates.crt")

	// Check if already linked/copied
	if _, err := os.Stat(targetCert); err == nil {
		slog.Debug("SSL certificates already configured", "path", targetCert)
		return targetCert, nil
	}

	// Create ssl certs directory
	if err := os.MkdirAll(sslDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create ssl certs directory %s: %w", sslDir, err)
	}

	// Verify directory was created
	if info, err := os.Stat(sslDir); err != nil {
		return "", fmt.Errorf("ssl directory does not exist after mkdir: %w", err)
	} else if !info.IsDir() {
		return "", fmt.Errorf("ssl path exists but is not a directory: %s", sslDir)
	}

	// Try to symlink first (saves space)
	// Remove existing symlink/file if it exists (broken symlink check)
	os.Remove(targetCert)

	relPath := filepath.Join("..", "..", "tls", "cert.pem")
	if err := os.Symlink(relPath, targetCert); err != nil {
		// If symlink fails, copy the file
		slog.Debug("symlink failed, copying certificate file", "error", err)
		certData, err := os.ReadFile(sourceCert)
		if err != nil {
			return "", fmt.Errorf("failed to read source cert %s: %w", sourceCert, err)
		}
		if err := os.WriteFile(targetCert, certData, 0644); err != nil {
			return "", fmt.Errorf("failed to write cert to %s: %w", targetCert, err)
		}
		slog.Info("copied SSL certificates", "from", sourceCert, "to", targetCert, "size", len(certData))
	} else {
		slog.Info("symlinked SSL certificates", "from", relPath, "to", targetCert)
	}

	return targetCert, nil
}

func (d *Driver) Which(ctx context.Context, name string) (string, error) {
	// Custom Which implementation to avoid SIGSYS errors on Android/Termux
	// Do not use os/exec.LookPath as it can trigger SIGSYS on Android with Go 1.24+

	if filepath.IsAbs(name) {
		if _, err := os.Stat(name); err == nil {
			slog.Debug("which", "binary", name, "result", name)
			return name, nil
		}
		slog.Debug("which", "binary", name, "result", api.ErrBinaryNotFound)
		return "", fmt.Errorf("%w: %s", api.ErrBinaryNotFound, name)
	}

	path := os.Getenv("PATH")
	if env, ok := ctx.Value(types.EnvKey).([]string); ok {
		for _, e := range env {
			if strings.HasPrefix(e, "PATH=") {
				path = strings.TrimPrefix(e, "PATH=")
				break
			}
		}
	}

	for _, dir := range filepath.SplitList(path) {
		fullPath := filepath.Join(dir, name)
		if info, err := os.Stat(fullPath); err == nil && !info.IsDir() {
			slog.Debug("which", "binary", name, "result", fullPath)
			return fullPath, nil
		}
	}
	slog.Debug("which", "binary", name, "result", api.ErrBinaryNotFound)
	return "", fmt.Errorf("%w: %s", api.ErrBinaryNotFound, name)
}

func init() {
	driver.Register[execdriver.Driver](&Provider{})
}
