package main

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_codebase "github.com/lucasew/workspaced/cmd/workspaced/codebase"
	pkg_driver "github.com/lucasew/workspaced/cmd/workspaced/driver"
	pkg_experiments "github.com/lucasew/workspaced/cmd/workspaced/experiments"
	pkg_home "github.com/lucasew/workspaced/cmd/workspaced/home"
	pkg_init "github.com/lucasew/workspaced/cmd/workspaced/init"
	pkg_is "github.com/lucasew/workspaced/cmd/workspaced/is"
	pkg_mod "github.com/lucasew/workspaced/cmd/workspaced/mod"
	pkg_open "github.com/lucasew/workspaced/cmd/workspaced/open"
	pkg_selfinstall "github.com/lucasew/workspaced/cmd/workspaced/selfinstall"
	pkg_selfupdate "github.com/lucasew/workspaced/cmd/workspaced/selfupdate"
	pkg_svc "github.com/lucasew/workspaced/cmd/workspaced/svc"
	pkg_system "github.com/lucasew/workspaced/cmd/workspaced/system"
	pkg_tool "github.com/lucasew/workspaced/cmd/workspaced/tool"
	pkg_utils "github.com/lucasew/workspaced/cmd/workspaced/utils"
)

func init() {
	Registry.FromGetter(pkg_codebase.GetCommand)
	Registry.FromGetter(pkg_driver.GetCommand)
	Registry.FromGetter(pkg_experiments.GetCommand)
	Registry.FromGetter(pkg_home.GetCommand)
	Registry.FromGetter(pkg_init.GetCommand)
	Registry.FromGetter(pkg_is.GetCommand)
	Registry.FromGetter(pkg_mod.GetCommand)
	Registry.FromGetter(pkg_open.GetCommand)
	Registry.FromGetter(pkg_selfinstall.GetCommand)
	Registry.FromGetter(pkg_selfupdate.GetCommand)
	Registry.FromGetter(pkg_svc.GetCommand)
	Registry.FromGetter(pkg_system.GetCommand)
	Registry.FromGetter(pkg_tool.GetCommand)
	Registry.FromGetter(pkg_utils.GetCommand)
}
