package main

// this file is generated by pkg/devtools/autoregistry.go, do not edit manually
import (
	pkg_codebase "workspaced/cmd/workspaced/codebase"
	pkg_driver "workspaced/cmd/workspaced/driver"
	pkg_home "workspaced/cmd/workspaced/home"
	pkg_init "workspaced/cmd/workspaced/init"
	pkg_is "workspaced/cmd/workspaced/is"
	pkg_mod "workspaced/cmd/workspaced/mod"
	pkg_open "workspaced/cmd/workspaced/open"
	pkg_selfinstall "workspaced/cmd/workspaced/selfinstall"
	pkg_selfupdate "workspaced/cmd/workspaced/selfupdate"
	pkg_svc "workspaced/cmd/workspaced/svc"
	pkg_system "workspaced/cmd/workspaced/system"
	pkg_tool "workspaced/cmd/workspaced/tool"
	pkg_utils "workspaced/cmd/workspaced/utils"
)

func init() {
	Registry.FromGetter(pkg_codebase.GetCommand)
	Registry.FromGetter(pkg_driver.GetCommand)
	Registry.FromGetter(pkg_home.GetCommand)
	Registry.FromGetter(pkg_init.GetCommand)
	Registry.FromGetter(pkg_is.GetCommand)
	Registry.FromGetter(pkg_mod.GetCommand)
	Registry.FromGetter(pkg_open.GetCommand)
	Registry.FromGetter(pkg_selfinstall.GetCommand)
	Registry.FromGetter(pkg_selfupdate.GetCommand)
	Registry.FromGetter(pkg_svc.GetCommand)
	Registry.FromGetter(pkg_system.GetCommand)
	Registry.FromGetter(pkg_tool.GetCommand)
	Registry.FromGetter(pkg_utils.GetCommand)
}
