package main

import (
	"bufio"
	"context"
	"fmt"
	"iter"
	"log/slog"
	"os"
	"path"
	"path/filepath"
	"strings"
	"workspaced/pkg/git"
	"workspaced/pkg/logging"

	"github.com/spf13/cobra"
)

type DetectedRoot struct {
	Dir        string
	Package    string
	ImportPath string
}

func ExtractPackage(ctx context.Context, gofile string) (string, error) {
	f, err := os.Open(gofile)
	if err != nil {
		return "", err
	}
	defer logging.Close(ctx, f)
	scanner := bufio.NewScanner(f)
	scanner.Scan()
	parts := strings.Split(scanner.Text(), " ")
	return strings.TrimSpace(parts[1]), nil

}

func (r DetectedRoot) Children(ctx context.Context) (iter.Seq[DetectedRoot], error) {
	items, err := filepath.Glob(fmt.Sprintf("%s/*/root.go", r.Dir))
	if err != nil {
		return nil, err
	}
	return func(yield func(DetectedRoot) bool) {
		for _, item := range items {
			dirname := path.Base(path.Dir(item))
			dir := path.Join(r.Dir, dirname)
			file := path.Join(dir, "root.go")
			pkg, err := ExtractPackage(ctx, file)
			if err != nil {
				panic(err)
			}
			if !yield(DetectedRoot{
				Dir:        dir,
				ImportPath: fmt.Sprintf("%s/%s", r.ImportPath, dirname),
				Package:    pkg,
			}) {
				return
			}
		}
	}, nil

}

func HandleRegistryCodegen(ctx context.Context, r DetectedRoot) error {
	prelude := path.Join(r.Dir, "prelude.go")

	childrenIter, err := r.Children(ctx)
	if err != nil {
		return err
	}
	children := []DetectedRoot{}
	for child := range childrenIter {
		children = append(children, child)
	}
	if len(children) == 0 {
		return nil
	}

	f, err := os.Create(prelude)
	if err != nil {
		return err
	}
	defer logging.Close(ctx, f)
	if _, err := fmt.Fprintf(f, "package %s\n", r.Package); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "// this file is generated by pkg/devtools/autoregistry.go, do not edit manually\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "import (\n"); err != nil {
		return err
	}
	for _, c := range children {
		if _, err := fmt.Fprintf(f, "\tpkg_%s \"%s\"\n", c.Package, c.ImportPath); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(f, ")\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(f, "func init() {\n"); err != nil {
		return err
	}
	for _, c := range children {
		if _, err := fmt.Fprintf(f, "\tRegistry.FromGetter(pkg_%s.GetCommand)\n", c.Package); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(f, "}\n"); err != nil {
		return err
	}
	for _, c := range children {
		if err := HandleRegistryCodegen(ctx, c); err != nil {
			return err
		}
	}
	return nil
}

var cmd = &cobra.Command{
	RunE: func(cmd *cobra.Command, args []string) error {
		wd, err := os.Getwd()
		if err != nil {
			return err
		}
		root, err := git.GetRoot(cmd.Context(), wd)
		if err != nil {
			return err
		}
		var RootDetected = DetectedRoot{
			Dir:        path.Join(root, "cmd", "workspaced"),
			Package:    "main",
			ImportPath: "workspaced/cmd/workspaced",
		}
		return HandleRegistryCodegen(cmd.Context(), RootDetected)
	},
}

func main() {
	rootLogger := slog.New(logging.NewPlainHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelInfo,
	}))
	rootCtx := logging.NewRootContext(rootLogger)

	cmd.SetContext(rootCtx)
	if err := cmd.ExecuteContext(rootCtx); err != nil {
		logging.ReportError(rootCtx, err, slog.String("context", "fatal error"))
	}
}
