package main

import (
	"bufio"
	"fmt"
	"iter"
	"log/slog"
	"os"
	"path"
	"path/filepath"
	"strings"
	"workspaced/pkg/git"

	"github.com/spf13/cobra"
)

type DetectedRoot struct {
	Dir        string
	Package    string
	ImportPath string
}

func ExtractPackage(gofile string) (string, error) {
	f, err := os.Open(gofile)
	if err != nil {
		return "", err
	}
	defer f.Close()
	scanner := bufio.NewScanner(f)
	scanner.Scan()
	parts := strings.Split(scanner.Text(), " ")
	return strings.TrimSpace(parts[1]), nil

}

func (r DetectedRoot) Children() (iter.Seq[DetectedRoot], error) {
	items, err := filepath.Glob(fmt.Sprintf("%s/*/root.go", r.Dir))
	if err != nil {
		return nil, err
	}
	return func(yield func(DetectedRoot) bool) {
		for _, item := range items {
			dirname := path.Base(path.Dir(item))
			dir := path.Join(r.Dir, dirname)
			file := path.Join(dir, "root.go")
			pkg, err := ExtractPackage(file)
			if err != nil {
				panic(err)
			}
			if !yield(DetectedRoot{
				Dir:        dir,
				ImportPath: fmt.Sprintf("%s/%s", r.ImportPath, dirname),
				Package:    pkg,
			}) {
				return
			}
		}
	}, nil

}

func HandleRegistryCodegen(r DetectedRoot) error {
	prelude := path.Join(r.Dir, "prelude.go")

	childrenIter, err := r.Children()
	if err != nil {
		return err
	}
	children := []DetectedRoot{}
	for child := range childrenIter {
		children = append(children, child)
	}
	if len(children) == 0 {
		return nil
	}

	f, err := os.Create(prelude)
	if err != nil {
		return err
	}
	defer f.Close()
	fmt.Fprintf(f, "package %s\n", r.Package)
	fmt.Fprintf(f, "\n")
	fmt.Fprintf(f, "// this file is generated by pkg/devtools/autoregistry.go, do not edit manually\n")
	fmt.Fprintf(f, "import (\n")
	for _, c := range children {
		fmt.Fprintf(f, "\tpkg_%s \"%s\"\n", c.Package, c.ImportPath)
	}
	fmt.Fprintf(f, ")\n")
	fmt.Fprintf(f, "\n")
	fmt.Fprintf(f, "func init() {\n")
	for _, c := range children {
		fmt.Fprintf(f, "\tRegistry.FromGetter(pkg_%s.GetCommand)\n", c.Package)
	}
	fmt.Fprintf(f, "}\n")
	for _, c := range children {
		if err := HandleRegistryCodegen(c); err != nil {
			return err
		}
	}
	return nil
}

var cmd = &cobra.Command{
	RunE: func(cmd *cobra.Command, args []string) error {
		wd, err := os.Getwd()
		if err != nil {
			return err
		}
		root, err := git.GetRoot(cmd.Context(), wd)
		if err != nil {
			return err
		}
		var RootDetected = DetectedRoot{
			Dir:        path.Join(root, "cmd", "workspaced"),
			Package:    "main",
			ImportPath: "workspaced/cmd/workspaced",
		}
		return HandleRegistryCodegen(RootDetected)
	},
}

func main() {
	if err := cmd.Execute(); err != nil {
		slog.Error("fatal error", "error", err)
	}
}
