package palette

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_drivers "github.com/lucasew/workspaced/cmd/workspaced/utils/palette/drivers"
	pkg_generate "github.com/lucasew/workspaced/cmd/workspaced/utils/palette/generate"
)

type children struct {
	Drivers     *pkg_drivers.Command
	ListDrivers *pkg_drivers.Command `cmd:"list-drivers"`
	Generate    *pkg_generate.Command
}
