package palette

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_drivers "workspaced/cmd/workspaced/utils/palette/drivers"
	pkg_generate "workspaced/cmd/workspaced/utils/palette/generate"
)

func init() {
	Registry.FromGetter(pkg_drivers.GetCommand)
	Registry.FromGetter(pkg_generate.GetCommand)
}
