package home

// this file is generated by internal/devtools/autoregistry, do not edit manually
import (
	pkg_apply "github.com/lucasew/workspaced/cmd/workspaced/home/apply"
	pkg_backup "github.com/lucasew/workspaced/cmd/workspaced/home/backup"
	pkg_config "github.com/lucasew/workspaced/cmd/workspaced/home/config"
	pkg_plan "github.com/lucasew/workspaced/cmd/workspaced/home/plan"
	pkg_sync "github.com/lucasew/workspaced/cmd/workspaced/home/sync"
)

func init() {
	Registry.FromGetter(pkg_apply.GetCommand)
	Registry.FromGetter(pkg_backup.GetCommand)
	Registry.FromGetter(pkg_config.GetCommand)
	Registry.FromGetter(pkg_plan.GetCommand)
	Registry.FromGetter(pkg_sync.GetCommand)
}
