package home

// this file is generated by pkg/devtools/autoregistry.go, do not edit manually
import (
	pkg_apply "workspaced/cmd/workspaced/home/apply"
	pkg_config "workspaced/cmd/workspaced/home/config"
	pkg_plan "workspaced/cmd/workspaced/home/plan"
	pkg_sync "workspaced/cmd/workspaced/home/sync"
)

func init() {
	Registry.FromGetter(pkg_apply.GetCommand)
	Registry.FromGetter(pkg_config.GetCommand)
	Registry.FromGetter(pkg_plan.GetCommand)
	Registry.FromGetter(pkg_sync.GetCommand)
}
