// Code generated by lewkit generate db. DO NOT EDIT.

package db

import (
	"context"
	db "github.com/lewtec/lewkit/x/db"
	_ "github.com/lewtec/lewkit/x/db/sqlite"
	sqlite "github.com/lucasew/workspaced/internal/db/sqlite"
)

type History struct {
	ID         int64
	Command    string
	Cwd        string
	Timestamp  int64
	ExitCode   int64
	DurationMs int64
}
type RecordHistoryParams struct {
	Command    string
	Cwd        string
	Timestamp  int64
	ExitCode   int64
	DurationMs int64
}
type SearchHistoryParams struct {
	Command string
	Limit   int64
}
type Queries interface {
	GetHistory(ctx context.Context, limit int64) ([]History, error)
	RecordHistory(ctx context.Context, arg RecordHistoryParams) error
	SearchHistory(ctx context.Context, arg SearchHistoryParams) ([]History, error)
}
type sqliteWrap struct {
	q *sqlite.Queries
}

func (w sqliteWrap) GetHistory(ctx context.Context, limit int64) ([]History, error) {
	v, err := w.q.GetHistory(ctx, limit)
	out := make([]History, len(v))
	for i := range v {
		out[i] = History(v[i])
	}
	return out, err
}
func (w sqliteWrap) RecordHistory(ctx context.Context, arg RecordHistoryParams) error {
	return w.q.RecordHistory(ctx, sqlite.RecordHistoryParams(arg))
}
func (w sqliteWrap) SearchHistory(ctx context.Context, arg SearchHistoryParams) ([]History, error) {
	v, err := w.q.SearchHistory(ctx, sqlite.SearchHistoryParams(arg))
	out := make([]History, len(v))
	for i := range v {
		out[i] = History(v[i])
	}
	return out, err
}
func New(url string) func(db.DBTX) Queries {
	return func(tx db.DBTX) Queries {
		switch db.Scheme(url) {
		case "sqlite":
			return sqliteWrap{q: sqlite.New(tx)}
		default:
			return nil
		}
	}
}
func Open(ctx context.Context, a *db.Arg[Queries]) error {
	return a.Open(ctx, FS, New(a.Value().URL()))
}
