package shell

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/lucasew/workspaced/internal/shellgen"
	"github.com/lucasew/workspaced/internal/version"
	envdriver "github.com/lucasew/workspaced/pkg/driver/env"
	execdriver "github.com/lucasew/workspaced/pkg/driver/exec"
	"github.com/lucasew/workspaced/pkg/logging"
	"github.com/lucasew/workspaced/pkg/taskgroup"
)

func getInitCommand() *cobra.Command {
	var force bool
	var profile bool

	cmd := &cobra.Command{
		Use:   "init [shell]",
		Short: "Generate shell initialization script",
		Long: `Generates shell initialization by concatenating prelude scripts.
Uses caching for performance - regenerates only when source files change.`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()
			logger := logging.GetLogger(ctx)
			startTime := time.Now()
			defer func() {
				if profile {
					logger.Info("shell init total time", "duration", time.Since(startTime))
				}
			}()
			shell := "bash"
			if len(args) > 0 {
				shell = args[0]
			}

			dotfilesRoot, err := findDotfilesRoot(ctx)
			if err != nil {
				return fmt.Errorf("find dotfiles root: %w", err)
			}

			preludeDir := filepath.Join(dotfilesRoot, "bin", "prelude")

			allFiles, err := filepath.Glob(filepath.Join(preludeDir, "*.sh"))
			if err != nil {
				return fmt.Errorf("list prelude files: %w", err)
			}

			preludeFingerprint, err := calculatePreludeFingerprint(allFiles)
			if err != nil {
				return fmt.Errorf("fingerprint prelude files: %w", err)
			}

			cacheDir := getCacheDir()
			if err := os.MkdirAll(cacheDir, 0755); err != nil {
				return fmt.Errorf("create cache directory: %w", err)
			}

			buildID := version.GetBuildID()
			cacheFile := filepath.Join(cacheDir, fmt.Sprintf("shell-init-%s-%s-%s.bash", shell, buildID, preludeFingerprint))

			if !force {
				if content, err := os.ReadFile(cacheFile); err == nil {
					if profile {
						logger.Info("shell init cache hit", "cache_file", cacheFile)
					}
					fmt.Print(string(content))
					return nil
				}
			}
			if profile {
				logger.Info("shell init cache miss, generating")
			}

			// Read all prelude files in parallel
			t1 := time.Now()
			if profile {
				logger.Info("shell init glob files", "duration", time.Since(t1), "files", len(allFiles))
			}

			// Separate .source.sh files from regular .sh files
			var files []string
			sourceFiles := make(map[string]string) // basename -> path

			for _, file := range allFiles {
				basename := filepath.Base(file)
				if strings.HasSuffix(basename, ".source.sh") {
					// Skip mise .source.sh as it's generated in Go
					if strings.Contains(basename, "mise") {
						continue
					}
					// Map the base name without .source.sh extension
					key := strings.TrimSuffix(basename, ".source.sh")
					sourceFiles[key] = file
				} else {
					files = append(files, file)
				}
			}
			sort.Strings(files)

			// Read all files in parallel (ordered map; Session is on CLI ctx).
			contents, err := taskgroup.Map[string, string]{
				Name:     "read-prelude",
				Items:    files,
				PoolKind: taskgroup.IO,
				TaskName: func(_ int, path string) string {
					return "read:" + filepath.Base(path)
				},
				Fn: func(ctx context.Context, s *taskgroup.Status, path string) (string, error) {
					content, err := os.ReadFile(path)
					if err != nil {
						return "", fmt.Errorf("read %s: %w", path, err)
					}
					return string(content), nil
				},
			}.Run(ctx)
			if err != nil {
				return err
			}
			contentMap := make(map[string]string, len(files))
			for i, path := range files {
				contentMap[path] = contents[i]
			}

			t2 := time.Now()
			sourceOutputs, err := executeSourceFiles(ctx, sourceFiles)
			if err != nil {
				return fmt.Errorf("execute source files: %w", err)
			}
			if profile {
				logger.Info("shell init executed .source.sh files", "duration", time.Since(t2), "files", len(sourceFiles))
			}

			var output strings.Builder
			output.WriteString("# Generated by workspaced shell init\n")
			output.WriteString("# This file is cached for performance\n")
			output.WriteString("# Commands executed in parallel for faster loading\n\n")

			// Generate all inline shell initialization code in parallel
			t3 := time.Now()
			inlineCode, err := shellgen.Generate(ctx)
			if err != nil {
				return fmt.Errorf("generate inline shell initialization: %w", err)
			}
			if profile {
				logger.Info("shell init generated inline code", "duration", time.Since(t3))
			}
			output.WriteString(inlineCode)

			for _, file := range files {
				basename := filepath.Base(file)
				baseKey := strings.TrimSuffix(basename, ".sh")

				// Skip files generated inline above
				if strings.Contains(basename, "workspaced-init") ||
					strings.Contains(basename, "workspaced-history") ||
					strings.Contains(basename, "interactive-uptime") {
					continue
				}

				// Check if there's a .source.sh file - if so, use ONLY its output
				if sourceOutput, hasSource := sourceOutputs[baseKey]; hasSource {
					fmt.Fprintf(&output, "# Source: %s (generated by %s.source.sh)\n", basename, baseKey)
					output.WriteString(sourceOutput)
					if !strings.HasSuffix(sourceOutput, "\n") {
						output.WriteString("\n")
					}
					output.WriteString("\n")
					continue
				}

				// Regular file processing
				content := contentMap[file]
				fmt.Fprintf(&output, "# Source: %s\n", basename)
				output.WriteString(content)

				if !strings.HasSuffix(content, "\n") {
					output.WriteString("\n")
				}
				output.WriteString("\n")
			}

			result := output.String()

			if err := os.WriteFile(cacheFile, []byte(result), 0644); err != nil {
				// Non-fatal, continue
				logger.Warn("failed to write shell init cache", "cache_file", cacheFile, "error", err)
			}

			fmt.Print(result)
			return nil
		},
	}

	cmd.Flags().BoolVarP(&force, "force", "f", false, "Force regeneration, ignore cache")
	cmd.Flags().BoolVarP(&profile, "profile", "p", false, "Show timing information for each step")

	return cmd
}

func findDotfilesRoot(ctx context.Context) (string, error) {
	// Use unified dotfiles detection
	root, err := envdriver.GetDotfilesRoot(ctx)
	if err != nil {
		return "", fmt.Errorf("dotfiles root not found: %w", err)
	}

	// Verify it has bin/prelude (shell init specific requirement)
	if info, err := os.Stat(filepath.Join(root, "bin", "prelude")); err == nil && info.IsDir() {
		return root, nil
	}

	return "", fmt.Errorf("dotfiles root found at %s but missing bin/prelude", root)
}

func getCacheDir() string {
	if xdgCache := os.Getenv("XDG_CACHE_HOME"); xdgCache != "" {
		return filepath.Join(xdgCache, "workspaced")
	}
	return filepath.Join(os.Getenv("HOME"), ".cache", "workspaced")
}

func calculatePreludeFingerprint(files []string) (string, error) {
	h := sha256.New()
	sort.Strings(files)
	for _, file := range files {
		content, err := os.ReadFile(file)
		if err != nil {
			return "", err
		}
		_, _ = h.Write([]byte(file))
		_, _ = h.Write([]byte{0})
		_, _ = h.Write(content)
		_, _ = h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))[:16], nil
}

// executeSourceFiles executes all .source.sh files in parallel and returns their outputs.
// Failures are soft: log a warning and omit that key so callers fall back to the .sh file.
func executeSourceFiles(ctx context.Context, sourceFiles map[string]string) (map[string]string, error) {
	if len(sourceFiles) == 0 {
		return make(map[string]string), nil
	}

	type sourceItem struct {
		key  string
		path string
	}
	type sourceOutput struct {
		output string
		ok     bool
	}

	items := make([]sourceItem, 0, len(sourceFiles))
	for key, path := range sourceFiles {
		items = append(items, sourceItem{key: key, path: path})
	}

	results, err := taskgroup.Map[sourceItem, sourceOutput]{
		Name:     "source-files",
		Items:    items,
		PoolKind: taskgroup.IO,
		TaskName: func(_ int, item sourceItem) string {
			return "source:" + item.key
		},
		Fn: func(ctx context.Context, s *taskgroup.Status, item sourceItem) (sourceOutput, error) {
			logger := logging.GetLogger(ctx)
			cmd, err := execdriver.Run(ctx, "bash", item.path)
			if err != nil {
				logger.Warn("failed to execute .source.sh", "source", item.key+".source.sh", "error", err)
				return sourceOutput{}, nil
			}
			cmd.Env = os.Environ()
			output, err := cmd.Output()
			if err != nil {
				logger.Warn("failed to execute .source.sh", "source", item.key+".source.sh", "error", err)
				return sourceOutput{}, nil
			}
			return sourceOutput{output: string(output), ok: true}, nil
		},
	}.Run(ctx)
	if err != nil {
		return nil, err
	}

	outputMap := make(map[string]string, len(items))
	for i, item := range items {
		if results[i].ok {
			outputMap[item.key] = results[i].output
		}
	}
	return outputMap, nil
}
