name: Autorelease
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        description: "New version"
        required: true
        default: "next"
        type: choice
        options:
          - next
          - major
          - minor
          - patch

jobs:
  autorelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install mise
        uses: jdx/mise-action@e79ddf65a11cec7b0e882bedced08d6e976efb2d
        with:
          install: true

      - name: Install dependencies
        run: mise run install

      - name: Codegen
        run: mise run codegen

      - name: PR if Difference
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git checkout -b chore/codegen-${GITHUB_SHA}
            git add .
            git commit -m "chore: update generated code"
            git push origin chore/codegen-${GITHUB_SHA}
            gh pr create --title "chore: update generated code" --body "Autogenerated changes from codegen task." --base main --head chore/codegen-${GITHUB_SHA}
            echo "Changes detected and PR created. Exiting."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: CI
        run: mise run ci

      - name: Release
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
             NEW_VERSION=$(svu ${{ github.event.inputs.version }})
             git tag $NEW_VERSION
             git push origin $NEW_VERSION
             gh release create $NEW_VERSION --generate-notes
          else
             gh release create ${{ github.ref_name }} --generate-notes
          fi

      - name: Upload Artifacts
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        run: |
          goreleaser build --clean
          gh release upload $(svu current) dist/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
