name: Test Harness

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  test-harness:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version-file: 'go.mod'
        cache: true
    - name: Run test harness
      run: WORKSPACED_RUN_TEST_HARNESS=1 go test -v ./pkg/tool/harness_test.go
